FROM node:latest

# Create app directory
RUN mkdir -p /var/app/client && \
    apt-get update
WORKDIR /var/app/client

COPY client/package.json /var/app/client

EXPOSE 3000

RUN npm install

CMD npm start